// Automotive R&D/leadership contacts, sourced from the Clay "People -
// Automotive" export (People_-Automotive-Default-view-export, pulled
// 2026-08-07). Each person is tagged with:
//   groupId  -- which tracked group they belong to: "ktm", "bmw", "piaggio",
//               "ducati", "mvagusta" (not currently a tracked map group), or
//               "other" (not a target company at all -- see matchNote).
//   siteId   -- best-guess EU/UK plant, or "unmapped" if the location string
//               doesn't clearly point to one. Matching rule used:
//                 - Single-plant groups (Ducati: Borgo Panigale; BMW: Berlin)
//                   match on city OR region name, since there's no second
//                   site to confuse it with.
//                 - Multi-plant groups (KTM: Mattighofen vs Munderfing;
//                   Piaggio: 4 sites) only match on the literal plant/city
//                   name -- a country or nearby-but-different city is left
//                   "unmapped" rather than guessed, per your instruction not
//                   to guess the primary plant from thin data.
//   matchNote -- why a row landed where it did, especially for "unmapped"
//               rows and any judgment call worth a second look.
//
// Rows flagged "close call, worth a second look" are KTM AG employees in
// small Upper Austria villages immediately next to Mattighofen (Jeging,
// Mettmach, Sankt Johann am Walde) or a bit further out (Seewalchen). They
// were left unmapped under the strict city-match rule, but geographically
// they're plausibly Mattighofen commuters. Flip them to "ktm-mattighofen" if
// you want a looser radius rule instead of literal string matching.

export const automotivePeople = [
  { name: "Pierluigi Zampieri", title: "R&D Vehicle Director", company: "Ducati Motor Holding", location: "Greater Bologna Metropolitan Area, Italy", linkedin: "https://www.linkedin.com/in/pierluigizampieri/", groupId: "ducati", siteId: "ducati-borgopanigale", matchNote: "" },
  { name: "Antonio Mazzanti", title: "Head of Engine Testing", company: "Ducati Motor Holding", location: "San Lazzaro di Savena, Emilia-Romagna, Italy", linkedin: "https://www.linkedin.com/in/antonio-mazzanti-8048922a/", groupId: "ducati", siteId: "ducati-borgopanigale", matchNote: "Bologna-area suburb; single-site group, region-level match" },
  { name: "Piero Giusti", title: "CAD/PLM Manager - R&D", company: "Ducati Motor Holding", location: "Bologna, Emilia-Romagna, Italy", linkedin: "https://www.linkedin.com/in/pierogiusti/", groupId: "ducati", siteId: "ducati-borgopanigale", matchNote: "" },
  { name: "Davide Perni", title: "Ducati Corse Off-Road Technical Manager", company: "Ducati Motor Holding", location: "Bologna, Emilia-Romagna, Italy", linkedin: "https://www.linkedin.com/in/davide-perni-5b966446/", groupId: "ducati", siteId: "ducati-borgopanigale", matchNote: "" },
  { name: "Matias Spillman Daniele", title: "Senior Simulation Engineer - R&D - Structural Mechanics Simulation", company: "KTM AG", location: "Graz, Styria, Austria", linkedin: "https://www.linkedin.com/in/matias-spillman-daniele/", groupId: "ktm", siteId: "unmapped", matchNote: "Graz is not a KTM plant city; multi-site group, no guess" },
  { name: "Simone Franzetti", title: "Development Lead - Multistrada V2|Desert X", company: "Ducati Motor Holding", location: "Bologna, Emilia-Romagna, Italy", linkedin: "https://www.linkedin.com/in/simone-franzetti-b81129151/", groupId: "ducati", siteId: "ducati-borgopanigale", matchNote: "" },
  { name: "Louis Tri Widodo Hadi", title: "Profesional Consultant Level Expert and Safety Driving Coach", company: "Hyundai // PT Gatra Perdana Putra", location: "Surabaya, East Java, Indonesia", linkedin: "https://www.linkedin.com/in/louis-tri-widodo-hadi-89106584/", groupId: "other", siteId: "unmapped", matchNote: "Not a target company -- likely a false-positive Clay match, consider removing from the source list" },
  { name: "David Attisano", title: "Head of Data Analysis - Ducati Corse & R&D DMH", company: "Ducati Motor Holding", location: "Bologna, Emilia-Romagna, Italy", linkedin: "https://www.linkedin.com/in/davidattisano/", groupId: "ducati", siteId: "ducati-borgopanigale", matchNote: "" },
  { name: "John Ponjee", title: "Business Owner", company: "Vertigo Pacific Consultancy", location: "Arnhem-Nijmegen Region, Netherlands", linkedin: "https://www.linkedin.com/in/john-ponjee-4ba7755/", groupId: "other", siteId: "unmapped", matchNote: "Not a target company -- likely a false-positive Clay match, consider removing from the source list" },
  { name: "Thomas Oberascher", title: "Head of Digital Components (R&D SW and HW)", company: "KTM AG", location: "Salzburg, Salzburg, Austria", linkedin: "https://www.linkedin.com/in/thomas-oberascher-3a021340/", groupId: "ktm", siteId: "unmapped", matchNote: "Salzburg city is not a KTM plant; multi-site group, no guess" },
  { name: "Simone Di Piazza", title: "Head of Innovation and R&D Services", company: "Ducati Motor Holding", location: "Bologna, Emilia-Romagna, Italy", linkedin: "https://www.linkedin.com/in/simone-di-piazza-ba5ba118/", groupId: "ducati", siteId: "ducati-borgopanigale", matchNote: "" },
  { name: "David Bruna", title: "Team Leader Product Development", company: "KTM AG", location: "Greater Barcelona Metropolitan Area", linkedin: "https://www.linkedin.com/in/david-bruna-a500b72b/", groupId: "ktm", siteId: "unmapped", matchNote: "Barcelona is not a current KTM/GASGAS site" },
  { name: "Neville Peter Lewis", title: "Senior Research And Development Engineer", company: "KTM AG", location: "Wals-Siezenheim, Salzburg, Austria", linkedin: "https://www.linkedin.com/in/neville-peter-lewis/", groupId: "ktm", siteId: "unmapped", matchNote: "Salzburg-area suburb, not a plant city" },
  { name: "Alessandro Volpini", title: "Head of R&D", company: "MV Agusta Motor S.p.A.", location: "Fratta Todina, Umbria, Italia", linkedin: "https://www.linkedin.com/in/alessandro-volpini-935a5671/", groupId: "mvagusta", siteId: "unmapped", matchNote: "MV Agusta is independent again (Sardarov family / Art of Mobility), not a tracked group; its real plant is Varese, not Umbria" },
  { name: "Andreas Gruber", title: "TECHNICAL R&D PROJECT LEAD | LEAD ENGINEER DESIGN CHASSIS", company: "KTM AG", location: "Kuchl, Salzburg, Österreich", linkedin: "https://www.linkedin.com/in/andreas-gruber-5431-/", groupId: "ktm", siteId: "unmapped", matchNote: "Salzburg-area, not a plant city" },
  { name: "Christian Sams", title: "Head of R&D KTM X-Bow Mechanics + PM", company: "KTM AG", location: "Austria, Austria", linkedin: "https://www.linkedin.com/in/christian-sams-432724164/", groupId: "ktm", siteId: "unmapped", matchNote: "Country-only location" },
  { name: "Andreas Bleierer", title: "Chief Engineer", company: "KTM AG", location: "Mattighofen, Upper Austria, Austria", linkedin: "https://www.linkedin.com/in/andreas-bleierer-55b06514b/", groupId: "ktm", siteId: "ktm-mattighofen", matchNote: "" },
  { name: "Corinna Kern", title: "Team Lead R&D Controlling", company: "KTM AG", location: "Salzburg, Austria", linkedin: "https://www.linkedin.com/in/corinna-kern-a85443188/", groupId: "ktm", siteId: "unmapped", matchNote: "Salzburg, not a plant city" },
  { name: "Sophie Linsmayer", title: "Product Development", company: "KTM AG", location: "Germany, Germany", linkedin: "https://www.linkedin.com/in/sophie-greiner-54483046/", groupId: "ktm", siteId: "unmapped", matchNote: "Country-only location" },
  { name: "Davide Pazzaglia", title: "R&D Engine Design - Project Leader", company: "Ducati Motor Holding", location: "Bologna, Emilia-Romagna, Italy", linkedin: "https://www.linkedin.com/in/davide-pazzaglia-36885927/", groupId: "ducati", siteId: "ducati-borgopanigale", matchNote: "" },
  { name: "Marianna Carrè", title: "Senior R&D and Product Cost Controller", company: "Ducati Motor Holding", location: "Spilamberto, Emilia-Romagna, Italy", linkedin: "https://www.linkedin.com/in/marianna-carrè-0915a712b/", groupId: "ducati", siteId: "ducati-borgopanigale", matchNote: "Emilia-Romagna region match (single-site group)" },
  { name: "Eliseo Sciarretta", title: "Software and Track Tools R&D Manager", company: "Ducati Motor Holding", location: "Bologna, Emilia-Romagna, Italy", linkedin: "https://www.linkedin.com/in/eliseo-sciarretta-09868b9/", groupId: "ducati", siteId: "ducati-borgopanigale", matchNote: "" },
  { name: "Negroni Luciano", title: "dirigente R&D", company: "Ducati Motor Holding", location: "Bologna, Emilia-Romagna, Italy", linkedin: "https://www.linkedin.com/in/negroni-luciano-6a641431/", groupId: "ducati", siteId: "ducati-borgopanigale", matchNote: "" },
  { name: "Matteo Villano", title: "Head of Operations – Brazil", company: "KTM AG", location: "São Paulo, São Paulo, Brazil", linkedin: "https://www.linkedin.com/in/matteo-villano-041367/", groupId: "ktm", siteId: "unmapped", matchNote: "Brazil -- out of EU/UK scope" },
  { name: "Fabian Steinbacher", title: "Vice President Operations", company: "KTM AG", location: "Greater Salzburg, Austria", linkedin: "https://www.linkedin.com/in/fabian-steinbacher/", groupId: "ktm", siteId: "unmapped", matchNote: "Salzburg-area, not a plant city" },
  { name: "Luca Girardin", title: "Head of Operations", company: "MV Agusta Motor S.p.A.", location: "Varese, Lombardy, Italy", linkedin: "https://www.linkedin.com/in/luca-girardin-92803543/", groupId: "mvagusta", siteId: "unmapped", matchNote: "MV Agusta is independent, not tracked; Varese is their real plant city" },
  { name: "Attilio Guidetti", title: "Regional Service Manager APAC | Aftersales & Dealer Network Operations | Ducati Motor Holding", company: "Ducati Motor Holding", location: "Italy, Italy", linkedin: "https://www.linkedin.com/in/service-manager/", groupId: "ducati", siteId: "unmapped", matchNote: "Country-only location and an APAC-region title -- likely not Bologna-based despite the Ducati company match" },
  { name: "Vijay Jangra", title: "Manager - Global sourcing Cost engineering and Procurement", company: "KTM AG", location: "Pune District, Maharashtra, India", linkedin: "https://www.linkedin.com/in/vijay-jangra-22a884179/", groupId: "ktm", siteId: "unmapped", matchNote: "India -- out of EU/UK scope" },
  { name: "Sailesh Kumar", title: "Manager - Global sourcing Cost engineering and Procurement", company: "KTM AG", location: "Gurgaon, Haryana, India", linkedin: "https://www.linkedin.com/in/sailesh-kumar-89176876/", groupId: "ktm", siteId: "unmapped", matchNote: "India -- out of EU/UK scope" },
  { name: "Tejas Inamdar", title: "Manager - Cost Engineering", company: "KTM AG", location: "Pune Division, Maharashtra, India", linkedin: "https://www.linkedin.com/in/tejas-inamdar-8629bb29/", groupId: "ktm", siteId: "unmapped", matchNote: "India -- out of EU/UK scope" },
  { name: "Thomas Freidl", title: "Head of Infrastructure and Operations", company: "KTM AG", location: "Salzburg und Umgebung", linkedin: "https://www.linkedin.com/in/thomas-freidl-320bb2178/", groupId: "ktm", siteId: "unmapped", matchNote: "Salzburg-area, not a plant city" },
  { name: "Andreas Breit", title: "Senior Engineering Project Manager Diagnostic System", company: "KTM AG", location: "Austria", linkedin: "https://www.linkedin.com/in/andreas-breit-2301758a/", groupId: "ktm", siteId: "unmapped", matchNote: "Country-only location" },
  { name: "Luca Bettazzi", title: "Operations Project Manager", company: "Ducati Motor Holding", location: "Bologna, Emilia-Romagna, Italy", linkedin: "https://www.linkedin.com/in/luca-bettazzi-562a8b35/", groupId: "ducati", siteId: "ducati-borgopanigale", matchNote: "" },
  { name: "Aaron Noah", title: "Sales Operations Manager", company: "Ducati Motor Holding", location: "Bengaluru, Karnataka, India", linkedin: "https://www.linkedin.com/in/aaron-noah-b890b6142/", groupId: "ducati", siteId: "unmapped", matchNote: "India -- sales ops role, out of EU/UK plant scope" },
  { name: "Stefano Dimatteo", title: "Logistics Operations Manager", company: "Ducati Motor Holding", location: "Bologna, Emilia-Romagna, Italy", linkedin: "https://www.linkedin.com/in/stefano-dimatteo-67005712/", groupId: "ducati", siteId: "ducati-borgopanigale", matchNote: "" },
  { name: "Thomas Loßkarn", title: "Head of Cost Engineering", company: "KTM AG", location: "Greater Nuremberg Metropolitan Area, Germany", linkedin: "https://www.linkedin.com/in/thomas-loßkarn-0b43a4222/", groupId: "ktm", siteId: "unmapped", matchNote: "Germany -- not an Austria plant city" },
  { name: "Alessandro Flaiani", title: "Sales Operations Manager - Commercial After Sales", company: "Ducati Motor Holding", location: "Bologna, Emilia-Romagna, Italy", linkedin: "https://www.linkedin.com/in/alessandro-flaiani-76b04312/", groupId: "ducati", siteId: "ducati-borgopanigale", matchNote: "" },
  { name: "David Kindl", title: "Team Lead Feature Portfolio, Systems Engineering & Vehicle Integration", company: "KTM AG", location: "Seewalchen, Upper Austria, Austria", linkedin: "https://www.linkedin.com/in/david-kindl/", groupId: "ktm", siteId: "unmapped", matchNote: "Seewalchen is ~35km from Mattighofen -- close call, worth a second look" },
  { name: "Eduard Torrents", title: "Head of Operations & Quality", company: "GASGAS Motorcycles GmbH", location: "Barcelona, Catalonia, Spain", linkedin: "https://www.linkedin.com/in/eduard-torrents-b2800914/", groupId: "ktm", siteId: "unmapped", matchNote: "Barcelona was GASGAS's site before the 2026 consolidation to Austria; not a current site" },
  { name: "Matthias Maier", title: "Lead Enterprise Application Operations", company: "KTM AG", location: "Jeging, Upper Austria, Austria", linkedin: "https://www.linkedin.com/in/matthias-maier-a76438220/", groupId: "ktm", siteId: "unmapped", matchNote: "Jeging is immediately adjacent to Mattighofen -- close call, worth a second look" },
  { name: "Florian Wilhelm", title: "Head of Industrial Engineering", company: "KTM AG", location: "Mettmach, Upper Austria, Austria", linkedin: "https://www.linkedin.com/in/florian-wilhelm-94ab89191/", groupId: "ktm", siteId: "unmapped", matchNote: "Mettmach is immediately adjacent to Mattighofen -- close call, worth a second look" },
  { name: "Gianluca Negri", title: "Engine Design Dept. Head - Engineering Division", company: "MV Agusta Motor S.p.A.", location: "Varese, Lombardy, Italy", linkedin: "https://www.linkedin.com/in/gianluca-negri-6b43712b/", groupId: "mvagusta", siteId: "unmapped", matchNote: "MV Agusta is independent, not tracked; Varese is their real plant city" },
  { name: "Colin J Ballantyne", title: "Lead, Advanced Engineering", company: "KTM AG", location: "Asolo, Veneto, Italy", linkedin: "https://www.linkedin.com/in/colin-j-ballantyne-4899b660/", groupId: "ktm", siteId: "unmapped", matchNote: "Veneto, Italy -- unrelated region" },
  { name: "Christian Pauer", title: "Lead Industrial Engineering", company: "KTM AG", location: "Austria", linkedin: "https://www.linkedin.com/in/christian-pauer-a4bb981b4/", groupId: "ktm", siteId: "unmapped", matchNote: "Country-only location" },
  { name: "Davide Gianessi", title: "Manufacturing Engineering Manager_Engine assembly and machining department", company: "Ducati Motor Holding", location: "Bologna, Emilia-Romagna, Italy", linkedin: "https://www.linkedin.com/in/gianessi-davide-32391018/", groupId: "ducati", siteId: "ducati-borgopanigale", matchNote: "" },
  { name: "Harald Stempfer", title: "Senior Manager Industrial Engineering EAS", company: "KTM AG", location: "Sankt Johann am Walde, Upper Austria, Austria", linkedin: "https://www.linkedin.com/in/harald-stempfer-a986b514b/", groupId: "ktm", siteId: "unmapped", matchNote: "Same district as Mattighofen -- close call, worth a second look" },
  { name: "Carmen Suárez", title: "Sales Administration & Operations Manager", company: "KTM AG", location: "Toluca de Lerdo, México, Mexico", linkedin: "https://www.linkedin.com/in/carmen-suarezg/", groupId: "ktm", siteId: "unmapped", matchNote: "Mexico -- out of EU/UK scope" },
  { name: "Tanja Berger", title: "Projektleiter Industrial Engineering", company: "KTM AG", location: "Mattighofen, Upper Austria, Austria", linkedin: "https://www.linkedin.com/in/tanja-berger-5627091b7/", groupId: "ktm", siteId: "ktm-mattighofen", matchNote: "" },
  { name: "Davide Baldanza", title: "HR MANAGER INDUSTRIAL OPERATIONS", company: "Ducati Motor Holding", location: "Bologna, Emilia-Romagna, Italy", linkedin: "https://www.linkedin.com/in/davide-baldanza-9a93abb/", groupId: "ducati", siteId: "ducati-borgopanigale", matchNote: "" },
  { name: "Alejandro Villamizar Llano", title: "Customer Service Team Lead", company: "KTM AG", location: "Medellín, Antioquia, Colombia", linkedin: "https://www.linkedin.com/in/alejandro-villamizar-llano/", groupId: "ktm", siteId: "unmapped", matchNote: "Colombia -- out of EU/UK scope" },
  { name: "Markus Luger", title: "HEAD OF PRODUCTION PLANNING / PROCESS ENGINEERING", company: "KTM AG", location: "Austria, Austria", linkedin: "https://www.linkedin.com/in/markus-luger-43b21244/", groupId: "ktm", siteId: "unmapped", matchNote: "Country-only location" },
];

export function getPeopleForSite(siteId) {
  return automotivePeople.filter((p) => p.siteId === siteId);
}

export function getPeopleForGroup(groupId) {
  return automotivePeople.filter((p) => p.groupId === groupId);
}
